### ISSUE TITLE
[Question] Merging OmniSketch Instances

### ISSUE THREAD

**Issue by michaelkoepf** [wiegerpunter/omnisketch#1]
Hi,

Is it possible to use OmniSketch in a data-parallel-fashion, this is, can OmniSketch instances be merged?

Thank you!

**Comment by wiegerpunter** [comment]
Hi,
Yes it should be, under the condition that you use the same hash functions in both instances (both attribute sketch hash functions and the K minwise hash function).
Let me know if you have other questions.
Wieger
